name: geofencing
dependencies:
- python
- pytest
- pytest-cov
- Flask
- Werkzeug
- pip:
  - gunicorn
  - connexion[swagger-ui]
  - marshmallow
  - mongoengine
  - marshmallow-mongoengine
  - python-dateutil
  - git+https://git@github.com/eurocontrol-swim/rest-client.git
  - git+https://git@github.com/eurocontrol-swim/swim-backend.git
